name: CICD Static Deployment

on:
  push:
    branches:
      - main
jobs:
  deploy:   
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP_ADDRESS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/Ecommerce
            docker-compose -f docker-compose.yml down
            git pull origin main
            docker-compose -f docker-compose.yml up --build -d
            sudo echo "Done"

            
            
