name: Deploy Django App

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin123
          POSTGRES_DB: app
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5


    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.13.0-alpha.2

    - name: Create virtual environment
      run: python -m venv venv

    - name: Activate virtual environment
      run: source venv/bin/activate

    - name: Install dependencies
      run: |
        pip install Django
        pip install django-countries
        pip install django-crispy-forms
        pip install django-environ
        pip install django-etc
        pip install django-filter
        pip install django-hitcount
        pip install django-multiselectfield
        pip install django-taggit
        pip install Pillow
        pip install psycopg2-binary
        pip install python-decouple
        pip install sqlparse
        pip install typing_extensions
        pip install tzdata
        
    - name: Run tests
      run: |
        python manage.py test core
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      - name: Build Docker Image
        run: |
          IMAGE_TAG=$(echo $GITHUB_SHA | head -c 7)
          docker build -t nahlooobi/xtremestoreapp:${IMAGE_TAG} .
          docker tag nahlooobi/xtremestoreapp:${IMAGE_TAG} nahlooobi/xtremestoreapp:latest

      - name: Push Docker Image
        run: docker push nahlooobi/xtremestoreapp:latest

      - name: Logout from Docker Hub
        run: docker logout

  deploy:
    runs-on: ubuntu-latest

    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Print Repository State
        run: git status

      - name: Deploy Via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP_ADDRESS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/Ecommerce
            docker-compose -f docker-compose.yml down
            git pull origin main
            docker-compose -f docker-compose.yml up --build -d



            
            
